# Copyright © 2025 Samuel Holt. All rights reserved.
# No licence is granted to copy, use, modify, distribute, or create derivative
# works of this file in any form, except with explicit written permission from
# the copyright holder.
import enum
from typing import List, Type, TypeVar

T = TypeVar("T", bound=enum.Enum)

def enum_values(enum_cls: Type[T]) -> List[str]:
    """Return the `.value` strings of any Enum subclass."""
    return [member.value for member in enum_cls]

class Method(enum.Enum):
    """Enum for different baselines."""
    RANDOM = "random"
    REACT = "react"
    REFLEXION = "reflexion"
    REACT_FACT_EXTRACTION_COMPRESS = "react_fact_extraction_compress"
    WORLD_MODEL_FACTS_PARALLEL_D_3 = "world_model_facts_parallel_d_3" # Main paper method
    WORLD_MODEL_FACTS_PARALLEL_D_1 = "world_model_facts_parallel_d_1" # Ablation
    WORLD_MODEL_FACTS_PARALLEL_D_2 = "world_model_facts_parallel_d_2" # Ablation

class Experiment(enum.Enum):
    """Enum for different Experiments."""
    BASELINES = "baselines"


class Envrionment(enum.Enum):
    """Enum for different environments."""
    GRID_4_H_3_S_2025 = "grid_4_h_3_s_2025"
    GRID_4_H_9_S_0 = "grid_4_h_9_s_0"
    GRID_8_H_5_S_0 = "grid_8_h_5_s_0"
    GRID_16_H_5_S_0 = "grid_16_h_5_s_0"
    ALF_MINI_ENV = "alf_mini_env"
    CRAFTER_MINI_5_S_0 = "crafter_mini_5_s_0"
    CRAFTER_MINI_10_S_2 = "crafter_mini_10_s_2"
    WEB_ENV_MINI = "web_env_mini"
    ALFWORD_TASK_0 = "alfworld_task_0"
    ALFWORD_TASK_1 = "alfworld_task_1"
    ALFWORD_TASK_2 = "alfworld_task_2"
    ALFWORD_TASK_3 = "alfworld_task_3"
    ALFWORD_TASK_4 = "alfworld_task_4"
    ALFWORD_TASK_5 = "alfworld_task_5"
    ALFWORD_TASK_6 = "alfworld_task_6"
    ALFWORD_TASK_7 = "alfworld_task_7"
    ALFWORD_TASK_8 = "alfworld_task_8"
    ALFWORD_TASK_9 = "alfworld_task_9"
    ALFWORD_TASK_10 = "alfworld_task_10"
    ALFWORD_TASK_11 = "alfworld_task_11"
    ALFWORD_TASK_12 = "alfworld_task_12"
    ALFWORD_TASK_13 = "alfworld_task_13"
    ALFWORD_TASK_14 = "alfworld_task_14"
    ALFWORD_TASK_15 = "alfworld_task_15"
    ALFWORD_TASK_16 = "alfworld_task_16"
    ALFWORD_TASK_17 = "alfworld_task_17"
    ALFWORD_TASK_18 = "alfworld_task_18"
    ALFWORD_TASK_19 = "alfworld_task_19"
    ALFWORD_TASK_20 = "alfworld_task_20"
    ALFWORD_TASK_21 = "alfworld_task_21"
    ALFWORD_TASK_22 = "alfworld_task_22"
    ALFWORD_TASK_23 = "alfworld_task_23"
    ALFWORD_TASK_24 = "alfworld_task_24"
    ALFWORD_TASK_25 = "alfworld_task_25"
    ALFWORD_TASK_26 = "alfworld_task_26"
    ALFWORD_TASK_27 = "alfworld_task_27"
    ALFWORD_TASK_28 = "alfworld_task_28"
    ALFWORD_TASK_29 = "alfworld_task_29"
    ALFWORD_TASK_30 = "alfworld_task_30"
    ALFWORD_TASK_31 = "alfworld_task_31"
    ALFWORD_TASK_32 = "alfworld_task_32"
    ALFWORD_TASK_33 = "alfworld_task_33"
    ALFWORD_TASK_34 = "alfworld_task_34"
    ALFWORD_TASK_35 = "alfworld_task_35"
    ALFWORD_TASK_36 = "alfworld_task_36"
    ALFWORD_TASK_37 = "alfworld_task_37"
    ALFWORD_TASK_38 = "alfworld_task_38"
    ALFWORD_TASK_39 = "alfworld_task_39"
    ALFWORD_TASK_40 = "alfworld_task_40"
    ALFWORD_TASK_41 = "alfworld_task_41"
    ALFWORD_TASK_42 = "alfworld_task_42"
    ALFWORD_TASK_43 = "alfworld_task_43"
    ALFWORD_TASK_44 = "alfworld_task_44"
    ALFWORD_TASK_45 = "alfworld_task_45"
    ALFWORD_TASK_46 = "alfworld_task_46"
    ALFWORD_TASK_47 = "alfworld_task_47"
    ALFWORD_TASK_48 = "alfworld_task_48"
    ALFWORD_TASK_49 = "alfworld_task_49"
    ALFWORD_TASK_50 = "alfworld_task_50"
    ALFWORD_TASK_51 = "alfworld_task_51"
    ALFWORD_TASK_52 = "alfworld_task_52"
    ALFWORD_TASK_53 = "alfworld_task_53"
    ALFWORD_TASK_54 = "alfworld_task_54"
    ALFWORD_TASK_55 = "alfworld_task_55"
    ALFWORD_TASK_56 = "alfworld_task_56"
    ALFWORD_TASK_57 = "alfworld_task_57"
    ALFWORD_TASK_58 = "alfworld_task_58"
    ALFWORD_TASK_59 = "alfworld_task_59"
    ALFWORD_TASK_60 = "alfworld_task_60"
    ALFWORD_TASK_61 = "alfworld_task_61"
    ALFWORD_TASK_62 = "alfworld_task_62"
    ALFWORD_TASK_63 = "alfworld_task_63"
    ALFWORD_TASK_64 = "alfworld_task_64"
    ALFWORD_TASK_65 = "alfworld_task_65"
    ALFWORD_TASK_66 = "alfworld_task_66"
    ALFWORD_TASK_67 = "alfworld_task_67"
    ALFWORD_TASK_68 = "alfworld_task_68"
    ALFWORD_TASK_69 = "alfworld_task_69"
    ALFWORD_TASK_70 = "alfworld_task_70"
    ALFWORD_TASK_71 = "alfworld_task_71"
    ALFWORD_TASK_72 = "alfworld_task_72"
    ALFWORD_TASK_73 = "alfworld_task_73"
    ALFWORD_TASK_74 = "alfworld_task_74"
    ALFWORD_TASK_75 = "alfworld_task_75"
    ALFWORD_TASK_76 = "alfworld_task_76"
    ALFWORD_TASK_77 = "alfworld_task_77"
    ALFWORD_TASK_78 = "alfworld_task_78"
    ALFWORD_TASK_79 = "alfworld_task_79"
    ALFWORD_TASK_80 = "alfworld_task_80"
    ALFWORD_TASK_81 = "alfworld_task_81"
    ALFWORD_TASK_82 = "alfworld_task_82"
    ALFWORD_TASK_83 = "alfworld_task_83"
    ALFWORD_TASK_84 = "alfworld_task_84"
    ALFWORD_TASK_85 = "alfworld_task_85"
    ALFWORD_TASK_86 = "alfworld_task_86"
    ALFWORD_TASK_87 = "alfworld_task_87"
    ALFWORD_TASK_88 = "alfworld_task_88"
    ALFWORD_TASK_89 = "alfworld_task_89"
    ALFWORD_TASK_90 = "alfworld_task_90"
    ALFWORD_TASK_91 = "alfworld_task_91"
    ALFWORD_TASK_92 = "alfworld_task_92"
    ALFWORD_TASK_93 = "alfworld_task_93"
    ALFWORD_TASK_94 = "alfworld_task_94"
    ALFWORD_TASK_95 = "alfworld_task_95"
    ALFWORD_TASK_96 = "alfworld_task_96"
    ALFWORD_TASK_97 = "alfworld_task_97"
    ALFWORD_TASK_98 = "alfworld_task_98"
    ALFWORD_TASK_99 = "alfworld_task_99"
    ALFWORD_TASK_100 = "alfworld_task_100"
    ALFWORD_TASK_101 = "alfworld_task_101"
    ALFWORD_TASK_102 = "alfworld_task_102"
    ALFWORD_TASK_103 = "alfworld_task_103"
    ALFWORD_TASK_104 = "alfworld_task_104"
    ALFWORD_TASK_105 = "alfworld_task_105"
    ALFWORD_TASK_106 = "alfworld_task_106"
    ALFWORD_TASK_107 = "alfworld_task_107"
    ALFWORD_TASK_108 = "alfworld_task_108"
    ALFWORD_TASK_109 = "alfworld_task_109"
    ALFWORD_TASK_110 = "alfworld_task_110"
    ALFWORD_TASK_111 = "alfworld_task_111"
    ALFWORD_TASK_112 = "alfworld_task_112"
    ALFWORD_TASK_113 = "alfworld_task_113"
    ALFWORD_TASK_114 = "alfworld_task_114"
    ALFWORD_TASK_115 = "alfworld_task_115"
    ALFWORD_TASK_116 = "alfworld_task_116"
    ALFWORD_TASK_117 = "alfworld_task_117"
    ALFWORD_TASK_118 = "alfworld_task_118"
    ALFWORD_TASK_119 = "alfworld_task_119"
    ALFWORD_TASK_120 = "alfworld_task_120"
    ALFWORD_TASK_121 = "alfworld_task_121"
    ALFWORD_TASK_122 = "alfworld_task_122"
    ALFWORD_TASK_123 = "alfworld_task_123"
    ALFWORD_TASK_124 = "alfworld_task_124"
    ALFWORD_TASK_125 = "alfworld_task_125"
    ALFWORD_TASK_126 = "alfworld_task_126"
    ALFWORD_TASK_127 = "alfworld_task_127"
    ALFWORD_TASK_128 = "alfworld_task_128"
    ALFWORD_TASK_129 = "alfworld_task_129"
    ALFWORD_TASK_130 = "alfworld_task_130"
    ALFWORD_TASK_131 = "alfworld_task_131"
    ALFWORD_TASK_132 = "alfworld_task_132"
    ALFWORD_TASK_133 = "alfworld_task_133"
    ALFWORD_TASK_134 = "alfworld_task_134"